USE metro;

--Inserta las estaciones del metro
INSERT INTO `stations`(name) VALUES
("Observatorio"),
("Tacubaya"),
("Juanacatlán"),
("Chapultepec"),
("Sevilla"),
("Insurgentes"),
("Cuauhtémoc"),
("Balderas"),
("Salto del Agua"),
("Isabel la Católica"),
("Pino Suárez"),
("Merced"),
("Candelaria"),
("San Lázaro"),
("Moctezuma"),
("Balbuena"),
("Blvd. Pto. Aéreo"),
("Gómez Farías"),
("Zaragoza"),
("Pantitlán"),
("Cuatro Caminos"),
("Panteones"),
("Tacuba"),
("Cuitláhuac"),
("Popotla"),
("Colegio Militar"),
("Normal"),
("San Cosme"),
("Revolución"),
("Hidalgo"),
("Bellas Artes"),
("Allende"),
("Zócalo"),
("San Antonio Abad"),
("Chabacano"),
("Viaducto"),
("Xola"),
("Villa de Cortés"),
("Nativitas"),
("Portales"),
("Ermita"),
("General Anaya"),
("Tasqueña"),
("Indios Verdes"),
("Deportivo 18 de marzo"),
("La Raza"),
("Tlatelolco"),
("Guerrero"),
("Juárez"),
("Niños Héroes"),
("Hospital General"),
("Centro Médico"),
("Etiopía/Plaza de la Transparencia"),
("Eugenia"),
("División del Norte"),
("Zapata"),
("Coyoacán"),
("Viveros/Derechos Humanos"),
("Miguel Ángel de Quevedo"),
("Copilco"),
("Universidad"),
("Martín Carrera"),
("Talismán"),
("Bondojito"),
("Consulado"),
("Canal del Norte"),
("Morelos"),
("Fray Servando"),
("Jamaica"),
("Santa Anita"),
("Pantitlán"),
("Hangares"),
("Terminal Aérea"),
("Oceanía"),
("Aragón"),
("Eduardo Molina"),
("Consulado"),
("Valle Gómez"),
("Misterios"),
("Autobuses del Norte"),
("Instituto del Petróleo"),
("Politécnico"),
("El Rosario"),
("Tezozómoc"),
("Azcapotzalco"),
("Ferrería/Arena Ciudad de México"),
("Norte 45"),
("Vallejo"),
("Lindavista"),
("La Villa-Basílica"),
("El Rosario"),
("Aquiles Serdán"),
("Camarones"),
("Refinería"),
("Tacuba"),
("San Joaquín"),
("Polanco"),
("Auditorio"),
("Constituyentes"),
("Tacubaya"),
("Garibaldi/Lagunilla"),
("Bellas Artes"),
("San Juan de Letrán"),
("Doctores"),
("Obrera"),
("Chabacano"),
("La Viga"),
("Santa Anita"),
("Tacubaya"),
("Patriotismo"),
("Chilpancingo"),
("Lázaro Cárdenas"),
("Jamaica"),
("Mixiuhca"),
("Velódromo"),
("Ciudad Deportiva"),
("Puebla"),
("Pantitlán"),
("Agrícola Oriental"),
("Canal de San Juan"),
("Tepalcates"),
("Guelatao"),
("Peñón Viejo"),
("Acatitla"),
("Santa Marta"),
("Los Reyes"),
("La Paz"),
("Buenavista"),
("Tepito"),
("Lagunilla"),
("Salto del Agua"),
("Coyuya"),
("Iztacalco"),
("Apatlaco"),
("Aculco"),
("Escuadrón 201"),
("Atlalilco"),
("Mixcoac"),
("Insurgentes Sur"),
("20 de Noviembre"),
("Zapata"),
("Parque de los Venados"),
("Eje Central"),
("Ermita"),
("Mexicaltzingo"),
("Culhuacán"),
("San Andrés Tomatlán"),
("Lomas Estrella");